FROM node:22-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY prisma ./prisma
COPY prisma.config.ts ./
COPY tsconfig.json ./
COPY tsconfig.build.json ./
COPY nest-cli.json ./
RUN sed -i 's/"deleteOutDir": true/"deleteOutDir": false/' nest-cli.json

COPY src ./src

RUN npx prisma generate

EXPOSE 3000

CMD ["npm", "run", "start:dev"]
